#!/usr/bin/env python3
"""Generate a per-repo AGENTS.md for repositories that do not ship one.

Adding a repo (Stash, Bitbucket, GitHub) through `bin/repos.py` or the dashboard's
Repositories view pulls its AGENTS.md/CLAUDE.md via the Scm port. Most repos in a real
estate have neither, and that repo then contributes **nothing** to the estate knowledge
every authoring phase reads — so tests get written without knowing the repo's surface,
its layout, or which suites already cover it.

This module fills that gap from what the platform already knows: the registry entry,
the harvested contract / route table, catalog evidence, coverage gaps, and (for test
repos) the layer conventions. It is **deterministic** — no model call, no API spend,
same inputs give the same file — which is what makes it safe to run automatically on
every repo add.

Two deliberate boundaries:

  * **Generated files never masquerade as repo-owned.** They are written to
    `knowledge/generated/<repo>/AGENTS.md`, not into the `knowledge/synced/` cache, and
    `repo_admin.repo_local_files()` ranks them BELOW anything real. The moment a team
    commits an AGENTS.md to the repo itself, theirs wins — silently and permanently.
  * **Nothing is pushed.** We write locally; `engine/gate/gate.sh` remains the only
    component that commits or pushes anything. The file is offered as a starting point
    a team can adopt into their own repo, not a change made on their behalf.

Once written, no further wiring is needed: `repo_admin.guidance_for()` picks it up,
`bin/gen_agents_md.py` folds it into the estate AGENTS.md, and that is injected as
context into every LLM phase — PR triage/generate and JIRA analyze/testplan/testdata/
generate alike. That is what makes it apply to application repos and E2E test repos
equally.

CLI:
  repo_guidance_gen.py <repo> [--force]     write one repo's AGENTS.md
  repo_guidance_gen.py --all [--force]      every registered repo missing one
  repo_guidance_gen.py <repo> --print       render to stdout, write nothing
"""
import os, pathlib, sys, time

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

ROOT = pathlib.Path(__file__).resolve().parents[2]
GEN_DIR = pathlib.Path(os.environ.get("AIQE_GENERATED_GUIDANCE_DIR")
                       or ROOT / "knowledge/generated")
MARKER = "AUTO-GENERATED by engine/lib/repo_guidance_gen.py"


# --------------------------------------------------------------------- inputs

def _registry():
    from registry import load_registry
    return load_registry()


def find_repo(name, reg=None):
    """(entry, kind) where kind is 'app' or 'test'; (None, None) if unregistered."""
    reg = reg or _registry()
    for r in reg.get("source_repositories", []):
        if r["name"] == name:
            return r, "app"
    for t in reg.get("test_repositories", []):
        if t["name"] == name:
            return t, "test"
    return None, None


def _harvest(entry):
    """Endpoints (backend) or UI routes (frontend) from the freshest clone we have.

    Mirrors bin/gen_agents_md.py rather than importing it: that module runs its work at
    import time, so importing it here would regenerate the estate file as a side effect.
    """
    import re
    art = entry.get("contract") if entry.get("type") == "backend" else entry.get("route_table")
    if not art:
        return []
    for base in (ROOT / "workspace/src" / entry["name"], ROOT / "demo" / entry["name"]):
        p = base / art
        if p.exists():
            text = p.read_text(encoding="utf-8", errors="ignore")
            if entry.get("type") == "backend":
                return re.findall(r"^\s{2}(/[^:\s]+):", text, re.M)
            return re.findall(r"path:\s*['\"]([^'\"]+)", text)
    return []


def _catalog():
    import glob, json
    out = []
    for f in sorted(glob.glob(str(ROOT / "catalog/*.jsonl"))):
        if pathlib.Path(f).name == "catalog.sample.jsonl":
            continue
        for line in open(f, encoding="utf-8"):
            if line.strip():
                try:
                    out.append(json.loads(line))
                except ValueError:
                    pass
    return out


def _conventions(layer):
    """The single-sourced layer conventions, so a generated file cannot fork them."""
    p = ROOT / f"skills/e2e-{layer}-conventions/SKILL.md"
    if not p.exists():
        return ""
    text = p.read_text(encoding="utf-8", errors="ignore")
    return text.split("---", 2)[2].strip() if text.startswith("---") else text.strip()


# --------------------------------------------------------------------- render

def _header(name, kind):
    return [
        f"# AGENTS.md — {name}",
        "",
        f"> {MARKER} because this repository does not ship an AGENTS.md or CLAUDE.md.",
        f"> Generated {time.strftime('%Y-%m-%d %H:%M:%S')} from the registry, the harvested",
        "> API/route surface and catalog evidence. Regenerate: `make repo-agents REPO="
        f"{name}`.",
        ">",
        "> **Commit a real AGENTS.md to this repository to replace it** — a repo-owned"
        " file always",
        "> wins over this one. Treat this as a starting point, not a source of truth.",
        "",
    ]


def _render_app(entry, reg):
    name = entry["name"]
    L = _header(name, "app")
    L.append("## What this repository is")
    L.append("")
    L.append(f"- **Kind**: {entry.get('type', 'unknown')} application repository")
    if entry.get("url"):
        L.append(f"- **Location**: `{entry['url']}` (`{entry.get('scm', '?')}`)")
    if entry.get("domains"):
        L.append(f"- **Business domains**: {', '.join(entry['domains'])}")
    if entry.get("consumes_services"):
        L.append(f"- **Consumes**: {', '.join(entry['consumes_services'])}")
    if entry.get("consumed_by"):
        L.append(f"- **Consumed by**: {', '.join(entry['consumed_by'])} — a contract "
                 "change here fans out to their E2E suites")
    if entry.get("testable_paths"):
        L.append(f"- **Testable paths**: {', '.join(f'`{p}`' for p in entry['testable_paths'])} "
                 "— changes outside these do not trigger test generation")
    L.append("")

    # Surface + which of it is already covered
    cat = _catalog()
    evidence = set()
    for e in cat:
        if name in e.get("mapping", {}).get("app_repos", []):
            ev = e.get("evidence", {})
            evidence.update(ev.get("endpoints", []) or [])
            evidence.update(ev.get("ui_routes", []) or [])
    surface = _harvest(entry)
    if surface:
        is_api = entry.get("type") == "backend"
        L.append(f"## {'API surface' if is_api else 'UI routes'} "
                 "(harvested — `[NO TEST]` marks a coverage gap)")
        L.append("")
        for s in surface:
            covered = any(s in str(e) for e in evidence)
            L.append(f"- `{s}`" + ("" if covered else "  **[NO TEST]**"))
        L.append("")
        L.append("Prioritise the `[NO TEST]` entries when adding coverage.")
        L.append("")

    covering = [t["name"] for t in reg.get("test_repositories", [])
                if name in (t.get("covers") or [])]
    L.append("## Where its tests live")
    L.append("")
    if covering:
        for t in covering:
            te = next(x for x in reg["test_repositories"] if x["name"] == t)
            L.append(f"- **{t}** ({te.get('layer', '?')}, {te.get('framework', '?')}) — "
                     f"specs under `{(te.get('layout') or {}).get('specs', '?')}`")
    else:
        L.append("- No E2E test repository currently covers this repo. Routing will ask "
                 "for clarification rather than guess — set a scope with "
                 f"`bin/repos.py scope <test-repo> {name}`.")
    L.append("")

    mapped = [e for e in cat
              if name in e.get("mapping", {}).get("app_repos", [])
              and e.get("mapping", {}).get("status") in ("auto", "confirmed")]
    if mapped:
        L.append("## Existing tests (extend these before writing new ones)")
        L.append("")
        for e in mapped[:25]:
            L.append(f"- `{e.get('file', '?')}` — {e.get('title', '?')}")
        if len(mapped) > 25:
            L.append(f"- … and {len(mapped) - 25} more (`bin/qa.py tests --app {name}`)")
        L.append("")

    L.append("## Rules for authoring against this repo")
    L.append("")
    L.append("- **Never modify application source here.** Tests are written in the E2E "
             "test repositories listed above; this repo is cloned read-only.")
    L.append("- Prefer **extending an existing spec** over creating a near-duplicate — "
             "check the list above first.")
    L.append("- Every new spec must ship a catalog sidecar entry in the same commit, or "
             "the gate rejects it (exit 4).")
    return L


def _render_test(entry, reg):
    name = entry["name"]
    layer = entry.get("layer", "api")
    layout = entry.get("layout") or {}
    L = _header(name, "test")
    L.append("## What this repository is")
    L.append("")
    L.append(f"- **Kind**: {layer.upper()} end-to-end test repository")
    if entry.get("url"):
        L.append(f"- **Location**: `{entry['url']}` (`{entry.get('scm', '?')}`)")
    L.append(f"- **Framework**: {entry.get('framework', 'unknown')}")
    if entry.get("jenkins_job"):
        L.append(f"- **CI job**: {entry['jenkins_job']}")
    L.append("")

    L.append("## Layout — where generated files must go")
    L.append("")
    if layout:
        labels = {"specs": "test specs", "fixtures": "fixtures / test data",
                  "pages": "page objects"}
        for k, v in layout.items():
            L.append(f"- `{v}` — {labels.get(k, k)}")
    else:
        L.append("- No layout declared in the registry. Set one with "
                 f"`bin/repos.py set {name} ...` so generation knows where to write.")
    L.append("- `catalog/` — the born-mapped sidecar entry for every new spec")
    L.append("")

    scope = entry.get("scope") or []
    covers = entry.get("covers") or []
    L.append("## Application repositories this suite is responsible for")
    L.append("")
    if covers:
        for a in covers:
            src = "declared scope" if a in scope else "catalog evidence"
            L.append(f"- **{a}** ({src})")
    else:
        L.append(f"- None yet. Declare responsibility with `bin/repos.py scope {name} "
                 "<app-repo,...>` — until then, routing cannot send work here.")
    L.append("")

    conv = _conventions(layer)
    if conv:
        L.append(f"## {layer.upper()} conventions")
        L.append("")
        L.append(f"<!-- single-sourced from skills/e2e-{layer}-conventions/SKILL.md -->")
        L.append("")
        L.append(conv)
        L.append("")

    L.append("## Gate rules that apply to every commit here")
    L.append("")
    L.append("- Writes stay inside this repository's test paths (exit 2).")
    L.append("- Every new spec ships a catalog sidecar entry in the same commit — "
             "\"born-mapped\" (exit 4).")
    L.append("- Changed specs must lint and actually pass against a provisioned app "
             "(exit 5).")
    L.append("- No secrets or PII in new content (exit 3).")
    L.append("- The gate is the only component that commits or pushes. Never run git "
             "yourself.")
    return L


def render(name, reg=None):
    """The AGENTS.md text for a repo. Raises KeyError if it is not registered."""
    reg = reg or _registry()
    entry, kind = find_repo(name, reg)
    if entry is None:
        raise KeyError(f"{name} is not in registry/repo-registry.yaml")
    lines = _render_app(entry, reg) if kind == "app" else _render_test(entry, reg)
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------- write

def _rel(p):
    """Repo-relative path for display, falling back to absolute.

    GEN_DIR is overridable via AIQE_GENERATED_GUIDANCE_DIR and may legitimately sit
    outside the checkout, where relative_to() raises rather than returning something
    useful."""
    try:
        return pathlib.Path(p).relative_to(ROOT).as_posix()
    except ValueError:
        return pathlib.Path(p).as_posix()


def generated_path(name):
    return GEN_DIR / name / "AGENTS.md"


def has_real_guidance(name):
    """True when the repo already provides its own AGENTS.md/CLAUDE.md.

    Asks repo_admin so we honour exactly the same precedence the phases see (clone,
    sync cache, demo fixture) — and ignore any file we generated ourselves.
    """
    try:
        import repo_admin
        for f in repo_admin.repo_local_files(name):
            if MARKER not in (f.get("text") or ""):
                return True
    except Exception:
        pass
    return False


def ensure(name, force=False, reg=None):
    """Generate this repo's AGENTS.md unless it has real guidance already.

    Returns {'repo', 'status', 'path'} where status is written | skipped_has_own |
    skipped_exists | unregistered. Never raises for an unregistered repo — callers run
    this opportunistically after an add and must not fail because of it.
    """
    entry, _ = find_repo(name, reg)
    if entry is None:
        return {"repo": name, "status": "unregistered", "path": None}
    if not force and has_real_guidance(name):
        return {"repo": name, "status": "skipped_has_own", "path": None}
    dest = generated_path(name)
    if dest.exists() and not force:
        return {"repo": name, "status": "skipped_exists",
                "path": _rel(dest)}
    text = render(name, reg)
    dest.parent.mkdir(parents=True, exist_ok=True)
    with open(dest, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    return {"repo": name, "status": "written", "path": _rel(dest)}


def ensure_all(force=False):
    reg = _registry()
    names = [r["name"] for r in reg.get("source_repositories", [])] + \
            [t["name"] for t in reg.get("test_repositories", [])]
    return [ensure(n, force=force, reg=reg) for n in names]


def generated_files(name):
    """[{path, text}] for repo_admin's precedence chain — [] when we made none."""
    p = generated_path(name)
    if not p.exists():
        return []
    return [{"path": _rel(p),
             "text": p.read_text(encoding="utf-8", errors="ignore")}]


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")     # Windows consoles default to cp1252
    argv = [a for a in sys.argv[1:] if not a.startswith("-")]
    force = "--force" in sys.argv
    if "--print" in sys.argv:
        print(render(argv[0]))
        sys.exit(0)
    rows = ensure_all(force=force) if "--all" in sys.argv else \
        [ensure(argv[0], force=force)] if argv else []
    if not rows:
        sys.exit(__doc__)
    for r in rows:
        print(f"{r['status']:<18} {r['repo']}" + (f"  -> {r['path']}" if r["path"] else ""))
