#!/usr/bin/env python3
"""Per-run artifact bundle over the durable B1 store (PRD B2).

The pipeline calls ``capture_phase`` at the phase boundary, where the exact
prompt and input files are known.  ``finalize`` writes one content-addressed
manifest containing references and hashes only; artifact bytes remain in B1.
"""
from __future__ import annotations

import datetime as dt
import hashlib
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import app_paths  # noqa: E402
import artifact_store  # noqa: E402
import fs_lock  # noqa: E402

SCHEMA = 1
EXPECTED_KINDS = (
    "estate-guidance", "repo-guidance", "conventions", "exemplar",
    "phase-context", "context-manifest", "extend-candidates",
    "requirements", "plan", "generated-skill",
)


class TaskBundleError(RuntimeError):
    """The bundle or one of its addressed entries is invalid."""


def _journal(root=ROOT, run_id: str | None = None) -> pathlib.Path:
    if run_id is None:
        return pathlib.Path(root) / "out/task-bundle-parts.json"
    token = hashlib.sha256(run_id.encode("utf-8")).hexdigest()
    return pathlib.Path(root) / f"out/task-bundle-parts-{token}.json"


def _logical_path(path: pathlib.Path, root=ROOT) -> str:
    path = path.resolve(strict=False)
    roots = ((pathlib.Path(root).resolve(), ""),
             (app_paths.state_root().resolve(), "state/"))
    for base, prefix in roots:
        try:
            return prefix + path.relative_to(base).as_posix()
        except ValueError:
            continue
    # Never persist an operator's absolute filesystem layout.
    return f"external/{path.name}"


def _kind(logical: str, content: bytes) -> tuple[str, str | None, str | None]:
    low = logical.lower()
    text_head = content[:500].decode("utf-8", errors="ignore")
    if low.endswith("agents.md") and "knowledge/generated/" in low:
        parts = logical.replace("\\", "/").split("/")
        repo = parts[parts.index("generated") + 1] if "generated" in parts else None
        return "repo-guidance", repo, "generated"
    if low.endswith("agents.md"):
        return "estate-guidance", None, None
    if "repo-conventions" in low:
        return "conventions", None, None
    if (".agents/skills/" in low
            and "AUTO-GENERATED by bin/gen_path_skills.py" in text_head):
        return "generated-skill", None, None
    if "requirements" in low:
        return "requirements", None, None
    if "testplan" in low or "/testplans/" in f"/{low}":
        return "plan", None, None
    if "extend-candidates" in low or "impact-candidates" in low:
        return "extend-candidates", None, None
    return "phase-context", None, None


def _input_sha(run_id: str, phase: str, role: str, logical: str,
               content_sha: str) -> str:
    raw = json.dumps([run_id, phase, role, logical, content_sha],
                     separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(raw).hexdigest()


def _minimal_ref(row: dict, *, phase: str | None, role: str,
                 logical: str, attempt: str) -> dict:
    return {"status": "produced", "artifact_kind": row["kind"],
            "logical_path": logical, "phase": phase, "role": role,
            "attempt": attempt, "reference_id": row["reference_id"],
            "blob_sha256": row["blob_sha256"], "size": row["size"]}


def _capture_bytes(content: bytes, *, run_id: str, key: str, phase: str,
                   role: str, logical: str, attempt: str,
                   kind: str | None = None, repo: str | None = None,
                   source_tier: str | None = None, root=ROOT) -> dict:
    kind = kind or _kind(logical, content)[0]
    sha = hashlib.sha256(content).hexdigest()
    try:
        kw = {"repo": repo} if repo else {"key": key}
        row = artifact_store.put(
            content, kind=kind, produced_by_run=run_id,
            inputs_sha=_input_sha(run_id, phase, role, logical, sha),
            source_tier=source_tier, root=root, **kw)
        if row is None:
            return {"status": "disabled", "artifact_kind": kind,
                    "logical_path": logical, "phase": phase, "role": role,
                    "attempt": attempt, "reason": "AIQE_ARTIFACT_STORE is disabled"}
        return _minimal_ref(row, phase=phase, role=role,
                            logical=logical, attempt=attempt)
    except artifact_store.ArtifactStoreError as exc:
        return {"status": "unavailable", "artifact_kind": kind,
                "logical_path": logical, "phase": phase, "role": role,
                "attempt": attempt, "reason": str(exc)[:300]}


def _parse_context_manifest(content: bytes, phase: str) -> dict | None:
    head = content[:8000].decode("utf-8", errors="replace")
    if "context-scope" not in head:
        return None
    kept = dropped = ""
    budget = used = None
    for line in head.splitlines():
        if "kept=" in line:
            kept = line.split("kept=", 1)[1].strip()
        elif "dropped=" in line:
            dropped = line.split("dropped=", 1)[1].strip()
        if "budget_tokens=" in line:
            try:
                budget = int(line.split("budget_tokens=", 1)[1].split()[0])
            except (IndexError, ValueError):
                budget = None
        if "used_chars=" in line:
            try:
                used = int(line.split("used_chars=", 1)[1].split()[0])
            except (IndexError, ValueError):
                used = None
    def clean(value):
        return [c.strip() for c in value.replace("-->", "").split(",")
                if c.strip()]
    return {"schema": SCHEMA, "phase": phase, "kept": clean(kept),
            "dropped": clean(dropped), "budget_tokens": budget,
            "used_chars": used}


def _capture_file(path, *, run_id: str, key: str, phase: str, role: str,
                  attempt: str, root=ROOT) -> tuple[dict, dict | None]:
    raw_path = pathlib.Path(path)
    if not raw_path.is_absolute():
        raw_path = pathlib.Path(root) / raw_path
    logical = _logical_path(raw_path, root)
    if not raw_path.is_file():
        return ({"status": "unavailable", "artifact_kind": "phase-context",
                 "logical_path": logical, "phase": phase, "role": role,
                 "attempt": attempt, "reason": "input file was not available"}, None)
    try:
        content = raw_path.read_bytes()
    except OSError as exc:
        return ({"status": "unavailable", "artifact_kind": "phase-context",
                 "logical_path": logical, "phase": phase, "role": role,
                 "attempt": attempt, "reason": f"input read failed: {exc.__class__.__name__}"},
                None)
    kind, repo, source_tier = _kind(logical, content)
    entry = _capture_bytes(
        content, run_id=run_id, key=key, phase=phase, role=role,
        logical=logical, attempt=attempt, kind=kind, repo=repo,
        source_tier=source_tier, root=root)
    manifest_entry = None
    parsed = (_parse_context_manifest(content, phase)
              if raw_path.name.startswith("context-") else None)
    if parsed:
        body = json.dumps(parsed, sort_keys=True, separators=(",", ":")).encode("utf-8")
        manifest_entry = _capture_bytes(
            body, run_id=run_id, key=key, phase=phase, role="context-manifest",
            logical=f"{logical}#manifest", attempt=attempt,
            kind="context-manifest", root=root)
    return entry, manifest_entry


def _read_journal(path: pathlib.Path, run_id: str, key: str) -> dict:
    doc = fs_lock.read_json_guarded(path, {})
    if not isinstance(doc, dict) or doc.get("schema", SCHEMA) != SCHEMA:
        doc = {}
    if doc and (doc.get("run_id") != run_id or doc.get("key") != key):
        raise TaskBundleError("capture journal belongs to another run")
    doc.setdefault("schema", SCHEMA)
    doc.setdefault("run_id", run_id)
    doc.setdefault("key", key)
    doc.setdefault("phases", {})
    doc.setdefault("artifacts", [])
    return doc


def capture_phase(run_id: str, key: str, phase: str, attempt: str,
                  prompt: str, inputs: list[str], root=ROOT) -> dict:
    """Capture the exact prompt and input files for one phase attempt."""
    if not artifact_store.enabled():
        return {"state": "disabled"}
    entries = []
    prompt_entry, _ = _capture_file(
        prompt, run_id=run_id, key=key, phase=phase, role="prompt",
        attempt=attempt, root=root)
    entries.append(prompt_entry)
    context = None
    for value in inputs:
        entry, manifest = _capture_file(
            value, run_id=run_id, key=key, phase=phase, role="input",
            attempt=attempt, root=root)
        entries.append(entry)
        if manifest:
            entries.append(manifest)
            context = {"status": manifest["status"],
                       "manifest": manifest, "input": entry}
        else:
            candidate = pathlib.Path(value)
            if not candidate.is_absolute():
                candidate = pathlib.Path(root) / candidate
            if candidate.resolve(strict=False) == app_paths.agents_file(root).resolve(
                    strict=False) and context is None:
                status = ("fallback" if entry.get("status") == "produced"
                          else "unavailable")
                context = {"status": status, "input": entry,
                           "reason": "full estate guidance was used; no scoped manifest"}
    path = _journal(root, run_id)
    with fs_lock.lock(path, timeout=30):
        doc = _read_journal(path, run_id, key)
        phase_doc = doc["phases"].setdefault(phase, {"attempts": []})
        phase_doc["attempts"].append(
            {"attempt": attempt, "inputs": entries, "context": context})
        doc["artifacts"].extend(entries)
        fs_lock.write_json_atomic(path, doc, sort_keys=True)
    return {"state": "captured", "phase": phase, "entries": len(entries)}


def _already(doc: dict, kind: str, logical: str) -> bool:
    return any(row.get("artifact_kind") == kind and row.get("logical_path") == logical
               and row.get("status") == "produced" for row in doc["artifacts"])


def _ensure_file(doc: dict, path, *, run_id: str, key: str, kind: str | None = None,
                 repo: str | None = None, source_tier: str | None = None,
                 root=ROOT) -> None:
    raw_path = pathlib.Path(path)
    if not raw_path.is_absolute():
        raw_path = pathlib.Path(root) / raw_path
    logical = _logical_path(raw_path, root)
    if kind and _already(doc, kind, logical):
        return
    if not raw_path.is_file():
        return
    content = raw_path.read_bytes()
    detected, detected_repo, detected_tier = _kind(logical, content)
    entry = _capture_bytes(
        content, run_id=run_id, key=key, phase="bundle", role="run-artifact",
        logical=logical, attempt="final", kind=kind or detected,
        repo=repo or detected_repo, source_tier=source_tier or detected_tier,
        root=root)
    doc["artifacts"].append(entry)


def _skips(root=ROOT) -> dict[str, str]:
    out = {}
    try:
        for line in (pathlib.Path(root) / "out/phase-skips.tsv").read_text(
                encoding="utf-8").splitlines():
            phase, _, reason = line.partition("\t")
            if phase:
                out[phase] = reason or "phase was skipped"
    except OSError:
        pass
    return out


def _resolved_repos(root=ROOT) -> list[str]:
    try:
        row = json.loads((pathlib.Path(root) / "out/resolve.contract.json").read_text(
            encoding="utf-8"))
        return sorted(set((row.get("source_repos") or []) +
                          (row.get("test_repos") or [])))
    except (OSError, ValueError, TypeError):
        return []


def finalize(run_id: str, mode: str, key: str, root=ROOT) -> dict:
    """Store one addressable manifest and return its run-record pointer."""
    if not artifact_store.enabled():
        return {"state": "disabled", "schema": SCHEMA,
                "reason": "AIQE_ARTIFACT_STORE is disabled"}
    path = _journal(root, run_id)
    with fs_lock.lock(path, timeout=30):
        doc = _read_journal(path, run_id, key)

    # Global run artifacts in the PRD's B1 scope.  Phase inputs already captured
    # are not re-referenced; `_already` preserves one provenance row per use.
    _ensure_file(doc, app_paths.agents_file(root), run_id=run_id, key=key,
                 kind="estate-guidance", root=root)
    for repo in _resolved_repos(root):
        _ensure_file(doc, app_paths.knowledge_dir("generated", root) / repo / "AGENTS.md",
                     run_id=run_id, key=key, kind="repo-guidance", repo=repo,
                     source_tier="generated", root=root)
    for skill in sorted((pathlib.Path(root) / ".agents/skills").glob(
            "e2e-*-conventions/SKILL.md")):
        _ensure_file(doc, skill, run_id=run_id, key=key,
                     kind="generated-skill", root=root)
    for candidate, kind in (
            (app_paths.specs_dir(root) / key / "requirements.yaml", "requirements"),
            (app_paths.testplans_dir(root) / f"{key}.md", "plan"),
            (pathlib.Path(root) / "out/impact-candidates.json", "extend-candidates")):
        _ensure_file(doc, candidate, run_id=run_id, key=key, kind=kind, root=root)
    for candidate in sorted((pathlib.Path(root) / "out").glob("repo-conventions*.md")):
        _ensure_file(doc, candidate, run_id=run_id, key=key,
                     kind="conventions", root=root)

    skips = _skips(root)
    phases = {}
    for phase, phase_doc in sorted(doc["phases"].items()):
        attempts = phase_doc.get("attempts") or []
        latest = attempts[-1] if attempts else {}
        entries = latest.get("inputs") or []
        if phase in skips:
            state, reason = "skipped", skips[phase]
        elif not entries or not any(e.get("status") == "produced" for e in entries):
            state, reason = "unavailable", "phase inputs were not captured"
        else:
            state, reason = "produced", None
        phases[phase] = {"state": state, "reason": reason,
                         "attempts": attempts, "context": latest.get("context")}
    for phase, reason in skips.items():
        phases.setdefault(phase, {"state": "skipped", "reason": reason,
                                  "attempts": [], "context": None})
    # A contract proves a phase ran. If capture has no corresponding row, say so.
    for contract in sorted((pathlib.Path(root) / "out").glob("*.contract.json")):
        phase = contract.name.removesuffix(".contract.json")
        if phase != "resolve":
            phases.setdefault(phase, {"state": "unavailable",
                                      "reason": "phase ran but capture was not recorded",
                                      "attempts": [], "context": None})

    coverage = {}
    for kind in EXPECTED_KINDS:
        rows = [row for row in doc["artifacts"] if row.get("artifact_kind") == kind]
        produced = [row for row in rows if row.get("status") == "produced"]
        if produced:
            coverage[kind] = {"state": "produced", "count": len(produced)}
        elif rows:
            coverage[kind] = {"state": "unavailable", "count": 0,
                              "reason": rows[0].get("reason") or "capture failed"}
        else:
            reason = ("standalone exemplars were not produced; any examples are "
                      "embedded in conventions" if kind == "exemplar"
                      else "this artifact was not produced for this run")
            coverage[kind] = {"state": "skipped", "count": 0, "reason": reason}

    manifest = {"schema": SCHEMA, "artifact": "task-bundle", "run_id": run_id,
                "mode": mode, "key": key,
                "produced_at": dt.datetime.now(dt.timezone.utc).isoformat(),
                "phases": phases, "coverage": coverage,
                "artifacts": doc["artifacts"]}
    body = json.dumps(manifest, sort_keys=True, separators=(",", ":")).encode("utf-8")
    inputs_sha = hashlib.sha256(
        json.dumps([run_id, mode, key, SCHEMA], separators=(",", ":")).encode()).hexdigest()
    row = artifact_store.put(body, kind="task-bundle", key=key,
                             produced_by_run=run_id, inputs_sha=inputs_sha, root=root)
    if row is None:
        return {"state": "disabled", "schema": SCHEMA,
                "reason": "AIQE_ARTIFACT_STORE is disabled"}
    return {"state": "produced", "schema": SCHEMA,
            "reference_id": row["reference_id"],
            "blob_sha256": row["blob_sha256"],
            "artifact_count": len(doc["artifacts"]),
            "phase_count": len(phases)}


def load(pointer: dict, root=ROOT) -> dict:
    if not isinstance(pointer, dict) or pointer.get("state") != "produced":
        raise TaskBundleError((pointer or {}).get("reason") or "task bundle unavailable")
    try:
        row, body = artifact_store.get(pointer.get("reference_id"), root=root)
    except artifact_store.ArtifactStoreError as exc:
        raise TaskBundleError(str(exc)) from exc
    if row.get("kind") != "task-bundle" or row.get("blob_sha256") != pointer.get(
            "blob_sha256"):
        raise TaskBundleError("task bundle pointer does not match stored manifest")
    try:
        manifest = json.loads(body.decode("utf-8"))
    except (UnicodeError, ValueError) as exc:
        raise TaskBundleError("task bundle manifest is not valid JSON") from exc
    if manifest.get("schema") != SCHEMA or manifest.get("artifact") != "task-bundle":
        raise TaskBundleError("task bundle schema is unsupported")
    return manifest


def context_manifests(pointer: dict, root=ROOT, *, expected_run_id: str | None = None,
                      expected_key: str | None = None) -> tuple[dict, str | None]:
    """Historical context evidence by phase, validated through B1 hashes."""
    try:
        manifest = load(pointer, root=root)
        if expected_run_id and manifest.get("run_id") != expected_run_id:
            raise TaskBundleError("task bundle run_id does not match the run record")
        if expected_key and manifest.get("key") != expected_key:
            raise TaskBundleError("task bundle key does not match the run record")
        out = {}
        for phase, phase_doc in (manifest.get("phases") or {}).items():
            context = phase_doc.get("context") or {}
            if context.get("status") == "fallback":
                out[phase] = {"kept": [], "dropped": [], "budget_tokens": None,
                              "used_chars": None, "full_estate": True}
                continue
            entry = context.get("manifest") or {}
            if entry.get("status") != "produced":
                continue
            row, body = artifact_store.get(entry["reference_id"], root=root)
            if row["blob_sha256"] != entry.get("blob_sha256"):
                raise TaskBundleError(f"context manifest pointer mismatch for {phase}")
            parsed = json.loads(body.decode("utf-8"))
            out[phase] = {"kept": parsed.get("kept") or [],
                          "dropped": parsed.get("dropped") or [],
                          "budget_tokens": parsed.get("budget_tokens"),
                          "used_chars": parsed.get("used_chars"),
                          "full_estate": False}
        return out, None
    except (artifact_store.ArtifactStoreError, KeyError, TaskBundleError,
            UnicodeError, ValueError) as exc:
        return {}, str(exc)[:300]


def main(argv) -> int:
    if len(argv) >= 2 and argv[1] == "capture-phase" and len(argv) >= 8:
        result = capture_phase(argv[2], argv[3], argv[4], argv[5], argv[6], argv[7:])
        print(json.dumps(result, sort_keys=True))
        return 0
    if len(argv) == 5 and argv[1] == "finalize":
        print(json.dumps(finalize(argv[2], argv[3], argv[4]), sort_keys=True))
        return 0
    print("usage: task_bundle.py capture-phase RUN KEY PHASE ATTEMPT PROMPT [INPUT ...]",
          file=sys.stderr)
    print("   or: task_bundle.py finalize RUN MODE KEY", file=sys.stderr)
    return 64


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
