#!/usr/bin/env bash
# Smoke + adversarial UAT for the CATALOG BOOTSTRAP CHAIN.
#
# The chain (§5.9.2) is what decides which app repos each test covers. `covers:`
# regenerates from its output and `covers:` decides routing, so a chain that
# silently produces less than it should quietly unroutes work — the one failure
# mode this platform cannot see from the inside.
#
# It had never been run by `make review`. Worse, it exists TWICE:
# catalog/bootstrap/run_bootstrap.sh (the real one, with the claude classify
# stage) and bin/demo-bootstrap.sh (a reimplementation for the demo estate).
# Only the demo copy ever ran, so a divergence was invisible by construction —
# and there was one: the real copy fixed a truncate-before-tier bug and carries
# a comment explaining why, while the demo copy still had it.
#
#   1 real chain     run_bootstrap.sh itself completes and produces mappings
#   2 no billing     mock mode must not invoke `claude` — the chain's stage 3
#                    called it regardless, so "mock" still billed a live account
#   3 relocation     output honours AIQE_CATALOG_DIR, and the working estate's
#                    catalog is untouched by an isolated run
#   4 clone fails    a failed clone must NOT truncate an existing catalog
#   5 no divergence  both chain copies run the same stages in the same order
#   6 write-then-move  both copies build the catalog off to the side first
#
# Run: make test-bootstrap
set -u
ROOT="$(cd "$(dirname "$0")/.." && pwd)"; cd "$ROOT"
fail=0
TMPD_POSIX=$(mktemp -d); trap 'rm -rf "$TMPD_POSIX"' EXIT
# TWO FORMS OF THE SAME DIRECTORY, and each is required somewhere the other
# breaks:
#
#   TMPD       native (C:/...) — every AIQE_*_DIR below is read by python3,
#              which on Windows is a native binary and cannot resolve a POSIX
#              /tmp/... path. Git Bash rewrites POSIX paths in the environment
#              only when it is itself the launcher, so with only this form the
#              suite passed from a shell and failed from any other parent.
#   TMPD_POSIX POSIX (/tmp/...) — PATH is colon-separated, so a native path
#              beginning `C:` splits into `C` and `/Users/...`. Prepending the
#              native form silently failed to shadow anything, and the fake
#              `claude` below was never found: the "nothing was billed" check
#              resolved the REAL CLI and passed while proving nothing.
TMPD=$(cd "$TMPD_POSIX" && pwd -W 2>/dev/null || printf '%s' "$TMPD_POSIX")
check() { if [ "$1" = "$2" ]; then echo "PASS $3"; else echo "FAIL $3 ($2, want $1)"; fail=1; fi; }

TREPO=e2e-api-tests-1
[ -d "demo/$TREPO" ] || { echo "FAIL demo estate missing demo/$TREPO"; exit 1; }

# Isolation: every mutable output the chain touches gets a temp home, so the
# working estate's catalog, registry, AGENTS.md and query index are unaffected.
# A registry COPY (not a stub) because Stage 5 rewrites covers: in place.
mkdir -p "$TMPD/cat" "$TMPD_POSIX/bin"
# The registry COPY starts with covers: BLANKED for the repo under test. It is
# regenerated by Stage 5, so leaving the committed value in place made the
# covers: check pass on data the run never produced — it stayed green through a
# chain that harvested nothing and attributed nothing.
python3 - registry/repo-registry.yaml "$TMPD/registry.yaml" "$TREPO" <<'PY'
import sys, yaml
reg = yaml.safe_load(open(sys.argv[1], encoding="utf-8"))
for t in reg["test_repositories"]:
    if t["name"] == sys.argv[3]:
        t["covers"] = []
open(sys.argv[2], "w", encoding="utf-8").write(yaml.safe_dump(reg, sort_keys=False))
PY
export AIQE_CATALOG_DIR="$TMPD/cat" \
       AIQE_REGISTRY_FILE="$TMPD/registry.yaml" \
       AIQE_AGENTS_FILE="$TMPD/AGENTS.md" \
       AIQE_CATALOG_DB="$TMPD/catalog.db"

# A `claude` that bills nothing but PROVES it was called. Stage 3 used to run
# the classifier in mock mode; the guard is only meaningful if something fails
# when it is removed.
cat > "$TMPD_POSIX/bin/claude" <<'SH'
#!/usr/bin/env bash
echo "CALLED" >> "$AIQE_SMOKE_CLAUDE_MARKER"
echo '{"result":"[]"}'
SH
chmod +x "$TMPD_POSIX/bin/claude"
export AIQE_SMOKE_CLAUDE_MARKER="$TMPD/claude-called"

# Snapshot the working estate so attack 3 can prove it was not written to.
REAL_BEFORE=$(md5sum catalog/*.jsonl registry/repo-registry.yaml 2>/dev/null | md5sum)

# --- 1 + 2. the real chain, under mock, must not call the classifier --------
PATH="$TMPD_POSIX/bin:$PATH" AIQE_MOCK=1 \
  bash catalog/bootstrap/run_bootstrap.sh "$TREPO" >"$TMPD/1.log" 2>&1
rc=$?
check 0 "$rc" "run_bootstrap.sh completes under mock (see $TMPD/1.log)"

rows=$(wc -l < "$TMPD/cat/$TREPO.jsonl" 2>/dev/null || echo 0)
[ "${rows:-0}" -gt 0 ] && r=ok || r="rows=$rows"
check ok "$r" "the chain produced catalog mappings ($rows rows)"

# Every row must carry the mapping shape the rest of the estate reads. A chain
# that emits rows nothing can parse is worse than one that emits none.
python3 - "$TMPD/cat/$TREPO.jsonl" <<'PY' >"$TMPD/shape.txt" 2>&1
import json, sys
bad = []
for i, l in enumerate(open(sys.argv[1], encoding="utf-8"), 1):
    if not l.strip():
        continue
    try:
        e = json.loads(l)
        m = e["mapping"]
        assert isinstance(m["app_repos"], list) and isinstance(m["confidence"], float)
        assert m["status"] in ("auto", "needs_review", "orphan", "confirmed", "pending")
        assert e["test_id"] and e["test_repo"] and e["file"]
    except Exception as exc:
        bad.append(f"line {i}: {exc}")
print("OK" if not bad else "\n".join(bad))
PY
check OK "$(cat "$TMPD/shape.txt")" "every mapping row has the shape the estate reads"

[ ! -f "$AIQE_SMOKE_CLAUDE_MARKER" ] && r=ok || r="claude was invoked"
check ok "$r" "mock mode calls no LLM (nothing is billed)"

# --- 3. relocation is real, and the working estate is untouched -------------
[ -f "$TMPD/cat/review/$TREPO-queue.csv" ] && r=ok || r=missing
check ok "$r" "review queue lands in the relocated catalog"

REAL_AFTER=$(md5sum catalog/*.jsonl registry/repo-registry.yaml 2>/dev/null | md5sum)
check "$REAL_BEFORE" "$REAL_AFTER" "an isolated run does not touch the working estate"

# The chain's Stage 5 must have regenerated covers: from the RELOCATED catalog.
python3 - "$TMPD/registry.yaml" "$TREPO" <<'PY' >"$TMPD/cov.txt" 2>&1
import sys, yaml
reg = yaml.safe_load(open(sys.argv[1], encoding="utf-8"))
t = next(x for x in reg["test_repositories"] if x["name"] == sys.argv[2])
print("OK" if t.get("covers") else "covers is empty - routing would find nothing")
PY
check OK "$(cat "$TMPD/cov.txt")" "covers: regenerated from the relocated catalog"

# --- 3b. attribution actually happened -------------------------------------
# The reason covers: was empty on the first real run of this chain: nothing in
# run_bootstrap.sh populated workspace/src/, so harvest_facts read no contracts,
# correlate attributed nothing, and every test tiered `orphan`. The chain still
# exited 0 and printed "Bootstrap complete". An all-orphan catalog is a valid
# OUTCOME (a repo whose tests cover nothing recognizable), which is why it could
# not be spotted from the output — so assert the positive case directly.
python3 - "$TMPD/cat/$TREPO.jsonl" <<'PY' >"$TMPD/attr.txt" 2>&1
import json, sys
rows = [json.loads(l) for l in open(sys.argv[1], encoding="utf-8") if l.strip()]
auto = [r for r in rows if r["mapping"]["status"] == "auto" and r["mapping"]["app_repos"]]
print("OK" if auto else
      f"0 of {len(rows)} tests attributed to an app repo - the chain harvested no facts")
PY
check OK "$(cat "$TMPD/attr.txt")" "tests are attributed to app repos, not all orphaned"

# harvest_facts must REFUSE rather than emit an empty fact set: continuing would
# catalog every test `orphan` and strip covers:, reporting an inability to read
# the app repos as a finding that the tests cover nothing (constitution C13).
rm -rf "$TMPD/emptysrc" && mkdir -p "$TMPD/emptysrc"
( cd "$TMPD/emptysrc" && mkdir -p engine workspace/src && cp -r "$ROOT/engine/lib" engine/ \
  && cp -r "$ROOT/registry" . 2>/dev/null
  python3 "$ROOT/catalog/bootstrap/harvest_facts.py" ) >"$TMPD/hf.out" 2>"$TMPD/hf.err"
hrc=$?
[ "$hrc" -eq 3 ] && grep -q "HARVEST_FAILED" "$TMPD/hf.err" && ! [ -s "$TMPD/hf.out" ] && r=ok \
  || r="rc=$hrc"
check ok "$r" "harvest_facts refuses (exit 3) when it can read no app repo at all"

# --- 3c. an EMPTY app-repo directory is not a checkout ----------------------
# Stage 0b skipped the clone when the directory existed. Windows leaves empty
# directories behind whenever a handle is open during a delete, and an
# interrupted clone leaves a partial one — either way the contract that
# attributes every test to that repo is never read, and the run produces the
# all-orphan catalog that strips covers:. Plant the exact state and assert the
# chain recovers rather than trusting the directory.
rm -rf workspace/src
mkdir -p workspace/src/orders-api workspace/src/catalog-api workspace/src/web-storefront-ui
PATH="$TMPD_POSIX/bin:$PATH" AIQE_MOCK=1 \
  bash catalog/bootstrap/run_bootstrap.sh "$TREPO" >"$TMPD/3c.log" 2>&1
rc=$?
attributed=$(python3 -c "
import json
rows=[json.loads(l) for l in open(r'$TMPD/cat/$TREPO.jsonl', encoding='utf-8') if l.strip()]
print(sum(1 for r in rows if r['mapping']['app_repos']))" 2>/dev/null || echo 0)
[ "$rc" -eq 0 ] && [ "${attributed:-0}" -gt 0 ] && r=ok || r="rc=$rc attributed=$attributed"
check ok "$r" "an empty app-repo dir is re-cloned, not mistaken for a checkout"

# --- 4. a failed clone must not truncate an existing catalog ----------------
# The documented reason the clone check is fatal: continuing with no repo used
# to leave Stage 4 writing an empty catalog, which stripped covers: and
# silently unrouted the repo. Assert against a catalog that already has rows.
BEFORE=$(wc -l < "$TMPD/cat/$TREPO.jsonl")
PATH="$TMPD_POSIX/bin:$PATH" AIQE_MOCK=1 \
  bash catalog/bootstrap/run_bootstrap.sh zz-no-such-demo-repo >"$TMPD/4.log" 2>&1
rc=$?
[ "$rc" -ne 0 ] && r=ok || r="rc=$rc"
check ok "$r" "an unclonable repo fails the chain loudly"
AFTER=$(wc -l < "$TMPD/cat/$TREPO.jsonl")
check "$BEFORE" "$AFTER" "a failed run leaves the existing catalog intact"

# --- 5. the two chain copies must not diverge ------------------------------
# Pin the STAGE SEQUENCE, not the text: the demo copy legitimately differs in
# how it obtains the repo (it copies demo/ and rebuilds git history) and it
# skips the LLM classify stage. Everything downstream of extract must match, in
# order, or a fix lands in one copy and not the other — which is exactly what
# happened.
# COMMENTS ARE STRIPPED FIRST. The first version of this grepped the raw file
# and reported a divergence that did not exist: bin/demo-bootstrap.sh mentions
# "correlate.py's git_history evidence" in a comment 15 lines above the stage
# that runs it, so the comment set the order. A check that cries wolf gets
# disabled, which costs more than never having written it.
stages() {
  sed 's/#.*//' "$1" \
    | grep -oE '(harvest_facts|extract|correlate|split_residue|tier|export_review_queue|regen_coverage|gen_agents_md|index_db)\.py' \
    | awk '!seen[$0]++'
}
A=$(stages catalog/bootstrap/run_bootstrap.sh)
B=$(stages bin/demo-bootstrap.sh)
if [ "$A" = "$B" ]; then r=ok; else
  r="divergent"; { echo "--- run_bootstrap.sh"; echo "$A"; echo "--- demo-bootstrap.sh"; echo "$B"; } >"$TMPD/5.log"
fi
check ok "$r" "both chain copies run the same stages in the same order (detail: $TMPD/5.log)"

# --- 6. write-then-move in BOTH copies -------------------------------------
# `> catalog/x.jsonl` truncates BEFORE tier.py runs, so a tier crash empties an
# existing catalog and silently unroutes the repo. The demo copy carried this
# bug for as long as it existed, because a fix cannot travel to a file nobody
# knows is a duplicate.
bad=""
for f in catalog/bootstrap/run_bootstrap.sh bin/demo-bootstrap.sh; do
  grep -qE 'tier\.py "\$WS" > "\$WS/tiered\.jsonl"' "$f" || bad="$bad $f"
  grep -qE '> *"?\$?\{?CAT_DIR\}?/?\$?\{?TREPO\}?|tier\.py "\$WS" >[^"]*catalog/' "$f" 2>/dev/null
  grep -qE 'tier\.py .* > .*catalog/' "$f" && bad="$bad $f(truncates)"
done
[ -z "$bad" ] && r=ok || r="$bad"
check ok "$r" "both copies tier to a temp file and move (no truncate-before-tier)"

echo
[ "$fail" -eq 0 ] && echo "bootstrap smoke: all checks passed" \
                  || echo "bootstrap smoke: FAILURES above"
exit "$fail"
