"""Regression tests for the Settings view backends: engine/lib/settings_store.py
(.env read/write with masked secrets) and engine/lib/demo_data.py (demo reset)."""
import pathlib, subprocess, sys

import pytest

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "engine/lib"))
import demo_data, settings_store


@pytest.fixture
def env_file(tmp_path, monkeypatch):
    f = tmp_path / ".env"
    monkeypatch.setenv("AIQE_ENV_FILE", str(f))
    return f


def test_save_and_get_roundtrip_masks_secrets(env_file):
    env_file.write_text("# my note\nJIRA_URL=https://old.example.com\nUNRELATED=keepme\n",
                        encoding="utf-8")
    settings_store.save({"JIRA_URL": "https://new.example.com",
                         "ATLASSIAN_MCP_TOKEN": "sekrit-123"})
    text = env_file.read_text(encoding="utf-8")
    assert "# my note" in text and "UNRELATED=keepme" in text     # preserved
    assert "JIRA_URL=https://new.example.com" in text             # replaced in place
    assert "ATLASSIAN_MCP_TOKEN=sekrit-123" in text               # appended
    flat = {f["env"]: f for s in settings_store.get_settings() for f in s["fields"]}
    assert flat["JIRA_URL"]["value"] == "https://new.example.com"
    tok = flat["ATLASSIAN_MCP_TOKEN"]
    assert tok["set"] is True and tok["value"] == ""              # write-only secret
    assert "sekrit" not in str(settings_store.get_settings())


def test_defaults_apply_when_unset(env_file):
    flat = {f["env"]: f for s in settings_store.get_settings() for f in s["fields"]}
    assert flat["AIQE_MOCK"]["value"] == "1"
    assert flat["SCM_KIND"]["value"] == "github"
    assert flat["ANTHROPIC_API_KEY"]["set"] is False


def test_save_rejects_unknown_key_bad_option_and_newlines(env_file):
    for updates in ({"NOT_A_SETTING": "x"}, {"SCM_KIND": "gitlab"},
                    {"JIRA_URL": "a\nb"}):
        with pytest.raises(SystemExit):
            settings_store.save(updates)
    assert not env_file.exists()                                  # nothing written


def test_inline_comments_stripped_on_read(env_file):
    env_file.write_text("CONFLUENCE_SPACE=ENG    # default space\n", encoding="utf-8")
    assert settings_store.load()["CONFLUENCE_SPACE"] == "ENG"


def test_every_spec_key_documented_in_env_example():
    example = (ROOT / ".env.example").read_text(encoding="utf-8")
    documented = {line.split("=", 1)[0].strip() for line in example.splitlines()
                  if "=" in line and not line.lstrip().startswith("#")}
    missing = set(settings_store.ALL_KEYS) - documented
    assert not missing, f".env.example is missing: {sorted(missing)}"


def _demo_tree(tmp_path):
    for rel in ["reports/runs/1-x.json", "reports/runs/1-x-repo.diff",
                "reports/runs/reviews.json", "reports/PROJ-1-repo.log",
                "reports/dashboard.html", "reports/exports/P-1-testplan.pdf",
                "testplans/PROJ-1.md", "testdata/PROJ-1/cases.json",
                "out/pr.diff", "workspace/tests/r/a.spec.js", "catalog/health.json",
                # state stores that used to survive a clear (see the regression test)
                "reports/plans/state.json", "reports/plans/PROJ-1.contract.json",
                "reports/openhands/state.json", "reports/inline/ADHOC-1.json",
                "knowledge/generated/some-repo/AGENTS.md",
                "knowledge/synced/some-repo/AGENTS.md", "knowledge/synced/state.json",
                # bootstrapped catalog — demo output, regenerated by demo-bootstrap
                "catalog/e2e-api-tests-1.jsonl", "catalog/review/e2e-api-tests-1-queue.csv",
                # estate / config / code — must survive
                "catalog/catalog.sample.jsonl", "catalog/schema.json",
                "catalog/bootstrap/tier.py", "catalog/review/export_review_queue.py",
                "registry/repo-registry.yaml", "AGENTS.md",
                "demo/orders-api/app.js", "knowledge/repos/orders-api.md"]:
        p = tmp_path / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text("x", encoding="utf-8")
    return tmp_path


def test_clear_demo_removes_generated_keeps_estate(tmp_path):
    root = _demo_tree(tmp_path)
    r = demo_data.clear(root=root)
    assert r["removed"] == 20
    for gone in ["reports/runs/1-x.json", "reports/runs/reviews.json",
                 "reports/PROJ-1-repo.log", "reports/dashboard.html",
                 "reports/exports/P-1-testplan.pdf", "testplans/PROJ-1.md",
                 "testdata/PROJ-1/cases.json", "out/pr.diff",
                 "workspace/tests/r/a.spec.js", "catalog/health.json",
                 "catalog/e2e-api-tests-1.jsonl",
                 "catalog/review/e2e-api-tests-1-queue.csv"]:
        assert not (root / gone).exists(), gone
    for kept in ["catalog/catalog.sample.jsonl",   # documentation fixture
                 "catalog/schema.json",
                 "catalog/bootstrap/tier.py",          # bootstrap CODE
                 "catalog/review/export_review_queue.py",
                 "registry/repo-registry.yaml",        # repo CONFIGURATION
                 "AGENTS.md", "demo/orders-api/app.js",
                 "knowledge/repos/orders-api.md"]:      # hand-authored team notes
        assert (root / kept).exists(), kept
    assert (root / "reports/runs").is_dir()                       # recreated empty


def test_clear_demo_leaves_no_state_store_behind(tmp_path):
    """Regression: 'Clear demo data' left four stores untouched.

    The stores are deliberately scattered — plan state sits outside reports/runs/ so
    the run-record glob skips it, OpenHands events have their own dir, guidance caches
    live under knowledge/ — and each one added after this module was written was
    silently missed. The worst was reports/plans/: an approval outlived the plan it
    approved, so generation could run against a sign-off for a plan that no longer
    existed."""
    root = _demo_tree(tmp_path)
    demo_data.clear(root=root)
    for gone in ["reports/plans/state.json", "reports/plans/PROJ-1.contract.json",
                 "reports/openhands/state.json", "reports/inline/ADHOC-1.json",
                 "knowledge/generated/some-repo/AGENTS.md",
                 "knowledge/synced/some-repo/AGENTS.md", "knowledge/synced/state.json"]:
        assert not (root / gone).exists(), f"survived the clear: {gone}"


def test_every_writable_state_store_is_a_clear_target():
    """Adding a new state store without adding it here is how this regressed.

    Keep this list in step with the stores the platform writes; if you add one,
    add it to demo_data.CLEAR_DIRS in the same change."""
    for rel in ("reports/runs", "reports/plans", "reports/openhands",
                "reports/inline", "reports/exports",
                "knowledge/generated", "knowledge/synced",
                "out", "workspace", "testplans", "testdata"):
        assert rel in demo_data.CLEAR_DIRS, f"{rel} is written but never cleared"
    assert "knowledge/repos" not in demo_data.CLEAR_DIRS
    assert not any(d == "knowledge" for d in demo_data.CLEAR_DIRS),         "clearing all of knowledge/ would delete hand-authored team notes"


def test_clear_demo_dry_run_touches_nothing(tmp_path):
    root = _demo_tree(tmp_path)
    r = demo_data.clear(root=root, dry=True)
    assert r["removed"] == 20
    assert (root / "reports/runs/1-x.json").exists()


def test_clear_demo_refuses_while_a_run_looks_active(tmp_path):
    root = _demo_tree(tmp_path)
    (root / "out/.pipeline.lock").mkdir(parents=True)
    with pytest.raises(SystemExit, match="looks active"):
        demo_data.clear(root=root)
    assert (root / "reports/runs/1-x.json").exists(), "nothing may be deleted"


def test_clear_demo_breaks_a_stale_lock(tmp_path):
    """A killed run leaves out/.pipeline.lock behind forever. Refusing on that made
    the Settings button fail permanently with a message that was untrue and gave
    the user no way out. Match pipeline.sh: older than the threshold == dead."""
    import os as _os, time as _t
    root = _demo_tree(tmp_path)
    lock = root / "out/.pipeline.lock"
    lock.mkdir(parents=True)
    old = _t.time() - (demo_data.STALE_LOCK_MINUTES + 5) * 60
    _os.utime(lock, (old, old))
    r = demo_data.clear(root=root)
    assert not lock.exists(), "a stale lock must be broken, not honoured"
    assert any("stale" in t for t in r["targets"])
    assert not (root / "reports/runs/1-x.json").exists(), "the clear must proceed"


def test_clear_demo_force_overrides_a_live_lock(tmp_path):
    root = _demo_tree(tmp_path)
    (root / "out/.pipeline.lock").mkdir(parents=True)
    r = demo_data.clear(root=root, force=True)
    assert any("force-removed" in t for t in r["targets"])
    assert not (root / "reports/runs/1-x.json").exists()


def test_clear_demo_dry_run_never_touches_the_lock(tmp_path):
    root = _demo_tree(tmp_path)
    lock = root / "out/.pipeline.lock"
    lock.mkdir(parents=True)
    r = demo_data.clear(root=root, dry=True, force=True)
    assert lock.exists(), "a dry run must not remove the lock either"
    # …and must not claim it did
    assert any("would be removed" in t for t in r["targets"]), r["targets"]
    assert not any(t.endswith("— removed)") for t in r["targets"])


def test_dashboard_renders_settings_view():
    r = subprocess.run([sys.executable, str(ROOT / "bin/dashboard.py")],
                       capture_output=True, text=True, cwd=ROOT,
                       stdin=subprocess.DEVNULL)
    assert r.returncode == 0, r.stderr
    page = (ROOT / "reports/dashboard.html").read_text(encoding="utf-8")
    assert 'data-view="settings"' in page
    assert 'id="clear-demo"' in page and "Danger zone" in page
    assert "loadSettings" in page                                 # JS wired in


def test_clear_demo_clears_the_bootstrapped_catalog_but_keeps_code_and_sample(tmp_path):
    """The reported bug: Test catalog + Coverage views looked untouched because the
    bootstrapped catalog JSONL survived. It is demo output (make demo-bootstrap
    regenerates it) — clear it, but never the sample fixture or the bootstrap code."""
    root = _demo_tree(tmp_path)
    demo_data.clear(root=root)
    assert not (root / "catalog/e2e-api-tests-1.jsonl").exists()
    assert not (root / "catalog/review/e2e-api-tests-1-queue.csv").exists()
    assert (root / "catalog/catalog.sample.jsonl").exists(), "sample fixture deleted"
    assert (root / "catalog/schema.json").exists()
    assert (root / "catalog/bootstrap/tier.py").exists(), "bootstrap CODE deleted"
    assert (root / "catalog/review/export_review_queue.py").exists()


def test_clear_demo_keeps_repository_configuration(tmp_path):
    """The registry is CONFIGURATION, not generated demo output. A real deployment's
    repos live here; a demo-reset click must never destroy it."""
    root = _demo_tree(tmp_path)
    demo_data.clear(root=root)
    assert (root / "registry/repo-registry.yaml").exists()
    assert "registry" not in demo_data.CLEAR_DIRS
    assert not any(pat.startswith("registry/") for pat, _ in demo_data.CLEAR_GLOBS)


def test_dashboard_reloads_after_clearing():
    """A destructive action that visibly does nothing is a bug: the dashboard is
    server-rendered, so without a reload the cleared views keep showing stale data —
    which is exactly why the user thought nothing was deleted."""
    src = (ROOT / "bin/dashboard.py").read_text(encoding="utf-8")
    i = src.index("/api/demo/clear")
    assert "location.reload()" in src[i:i + 2000], \
        "clear handler must reload so the reset is visible"


def test_server_runs_the_clear_as_a_subprocess():
    """A long-lived dashboard server froze demo_data's clear targets at startup
    (in-process import), so a server started before a fix kept clearing the OLD,
    incomplete set while the freshly-rendered page promised the new one — seen in the
    field as 'Clear demo data does not delete test catalog / test plans'. The server
    must therefore execute the clear via subprocess, like the page render."""
    src = (ROOT / "bin/dashboard_server.py").read_text(encoding="utf-8")
    i = src.index('"/api/demo/clear"')
    handler = src[i:i + 1600]
    assert "demo_data.py" in handler and "--json" in handler, \
        "clear must run as a subprocess so a running server picks up current code"
    assert "demo_data.clear(" not in handler, "in-process clear reintroduced"


def test_demo_data_json_mode_contract():
    """The server depends on --json emitting one JSON object and exit 9 on refusal."""
    import json as _json, subprocess as _sp, sys as _s
    # The CLI clears relative to the REPO root (a module constant), not cwd — so this
    # must ONLY ever run with --dry, or the test itself wipes the live demo estate.
    r = _sp.run([_s.executable, str(ROOT / "engine/lib/demo_data.py"), "--json", "--dry"],
                cwd=ROOT, capture_output=True, text=True, encoding="utf-8",
                stdin=_sp.DEVNULL)
    assert r.returncode == 0, r.stderr
    out = _json.loads(r.stdout.strip().splitlines()[-1])
    assert out["ok"] is True and "removed" in out and "targets" in out
